channels:
  - conda-forge
  - nodefaults

dependencies:
  # a more precise python pin is added in CI
  ### environment-base.yml ###
  - doit-with-toml
  - jupyterlab >=3.5.2,<4
  - pip
  - python >=3.8,<3.12
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=16,!=17.*,<19
  # build
  - jsonschema-gentypes
  - flit >=3.7.1
  - twine
  ### environment-build.yml ###
  ### environment-test.yml ###
  # test
  - coverage
  - hypothesis
  - pytest-asyncio
  - pytest-html
  ### environment-test.yml ###
  ### environment-robot.yml ###
  - robotframework >=6
  - robotframework-pabot
  # browser
  - firefox
  - geckodriver
  - robotframework-jupyterlibrary >=0.4.1
  - lxml
  ### environment-robot.yml ###
